cluster:
  providerIntegration:
    components:
      systemd:
        timesyncd:
          ntp:
            - "10.205.105.253"
global:
  connectivity:
    network:
      loadBalancers:
        vipSubnet: "10.205.9.254/24"
    proxy:
      enabled: true
      httpProxy: "http://10.205.105.253:3128"
      httpsProxy: "http://10.205.105.253:3128"
      noProxy: "test.gigantic.io,10.205.105.0/24,cd.neoedge.cloud"
    baseDomain: test.gigantic.io
  metadata:
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"
    name: "{{ .ClusterName }}"
  controlPlane:
    replicas: 3
    oidc:
      clientId: "dex-k8s-authenticator"
      groupsClaim: "groups"
      issuerUrl: "https://dex.gerbil.test.gigantic.io"
      usernameClaim: "email"
    machineTemplate:
      diskSizeGB: 30
      sizingPolicy: m1.large
  nodePools:
    worker:
      sizingPolicy: m1.large
      diskSizeGB: 30
      replicas: 2
  providerSpecific:
    org: GIANT_SWARM
    ovdc: Org-GIANT-SWARM
    site: "https://cd.neoedge.cloud"
    ovdcNetwork: GS-ISOLATED
    userContext:
      secretRef:
        secretName: vcd-credentials
