global:
  connectivity:
    network:
      loadBalancers:
        vipSubnet: "10.205.9.254/24"
    ntp:
      servers:
        - "10.205.105.253"
    proxy:
      enabled: true
    baseDomain: test.gigantic.io
  metadata:
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"
    name: "{{ .ClusterName }}"
  controlPlane:
    replicas: 3
    diskSizeGB: 30
    sizingPolicy: m1.large
    oidc:
      clientId: "dex-k8s-authenticator"
      groupsClaim: "groups"
      issuerUrl: "https://dex.gerbil.test.gigantic.io"
      usernameClaim: "email"
  nodePools:
    worker:
      sizingPolicy: m1.large
      diskSizeGB: 30
      replicas: 2
  providerSpecific:
    org: GIANT_SWARM
    ovdc: Org-GIANT-SWARM
    site: "https://cd.neoedge.cloud"
    ovdcNetwork: GS-ISOLATED
    userContext:
      secretRef:
        secretName: vcd-credentials
