global:
  metadata:
    name: "{{ .ClusterName }}"
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"
  providerSpecific:
    site: https://cd.neoedge.cloud
    userContext:
      secretRef:
        secretName: vcd-credentials
    org: GIANT_SWARM
    ovdc: Org-GIANT-SWARM
    ovdcNetwork: GS-ISOLATED
  connectivity:
    network:
      loadBalancers:
        vipSubnet: 10.205.9.254/24
    proxy:
      enabled: true
      httpProxy: http://10.205.105.253:3128
      httpsProxy: http://10.205.105.253:3128
      noProxy: test.gigantic.io,10.205.105.0/24,cd.neoedge.cloud
  controlPlane:
    machineTemplate:
      sizingPolicy: 4cpu/8GoRAM
      diskSizeGB: 50
    oidc:
      issuerUrl: https://dex.gerbil.test.gigantic.io
      clientId: dex-k8s-authenticator
      usernameClaim: email
      groupsClaim: groups
    replicas: 3
  nodePools:
    worker:
      sizingPolicy: m1.large
      diskSizeGB: 50
      replicas: 2

cluster:
  providerIntegration:
    components:
      systemd:
        ntpd:
          enabled: true
          servers:
            - address: 10.205.105.253
              minpoll: 4
              maxpoll: 4
