global:
  metadata:
    name: "{{ .ClusterName }}"
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"
  connectivity:
    network:
      loadBalancers:
        numberOfIps: 1
  controlPlane:
    machineTemplate:
      folder: e2e-tests
      numCPUs: 4
      memoryMiB: 8192
      diskGiB: 30
      network:
        devices:
          - networkName: v500-data
            dhcp4: true
  nodePools:
    worker:
      folder: e2e-tests
      numCPUs: 4
      memoryMiB: 16384
      diskGiB: 30
      network:
        devices:
          - networkName: v500-data
            dhcp4: true
      replicas: 2
