global:
  metadata:
    name: "{{ .ClusterName }}"
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"
  providerSpecific:
    subscriptionId: 6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3
    location: westeurope
  connectivity:
    bastion:
      enabled: true
  controlPlane:
    instanceType: Standard_B4als_v2
  nodePools:
    nodepool-0:
      instanceType: Standard_B4as_v2
      minSize: 2
      maxSize: 5
