global:
  metadata:
    name: "{{ .ClusterName }}"
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"

  providerSpecific:
    region: eu-north-1

  controlPlane:
    # disable logging to save cost
    logging:
      apiServer: false
      authenticator: false
      audit: false
      controllerManager: false

  nodePools:
    nodepool-0:
      instanceType: t3.xlarge
      rootVolumeSizeGB: 25
      minSize: 2
      maxSize: 5
      # Speed up the ASG cycle when upgrading to avoid having long running test case
      instanceWarmup: 180

  apps:
    externalDns:
      values:
        triggerLoopOnEvent: true
    clusterAutoscaler:
      values:
        configmap:
          # Prevent cluster-autoscaler from trying to scale down while we're in the middle of our scaling test
          scaleDownUnneededTime: 15m0s
