global:
  metadata:
    name: "{{ .ClusterName }}"
    description: "E2E Test cluster"
    organization: "{{ .Organization }}"

  providerSpecific:
    region: eu-central-1

  connectivity:
    topology:
      mode: GiantSwarmManaged
    vpcMode: private
    network:
      vpcCidr: 10.{{ index .ExtraValues "CIDRSecondOctet" }}.0.0/18
    subnets:
      - cidrBlocks:
          - availabilityZone: a
            cidr: 10.{{ index .ExtraValues "CIDRSecondOctet" }}.0.0/20
          - availabilityZone: b
            cidr: 10.{{ index .ExtraValues "CIDRSecondOctet" }}.16.0/20
          - availabilityZone: c
            cidr: 10.{{ index .ExtraValues "CIDRSecondOctet" }}.32.0/20
        isPublic: false
        tags:
          subnet.giantswarm.io/api-server-elb: 'true'
          subnet.giantswarm.io/bastion: 'true'
          subnet.giantswarm.io/control-plane: 'true'
          subnet.giantswarm.io/endpoints: 'true'
          subnet.giantswarm.io/ingress: 'true'
          subnet.giantswarm.io/tgw: 'true'
          subnet.giantswarm.io/workers: 'true'
    dns:
      mode: public
    proxy:
      enabled: true
      httpProxy: http://proxy.operations.awsprod.gigantic.io:4000
      httpsProxy: http://proxy.operations.awsprod.gigantic.io:4000

  controlPlane:
    instanceType: c5a.xlarge
    rootVolumeSizeGB: 10
    libVolumeSizeGB: 15
    etcdVolumeSizeGB: 50
    apiMode: private

  nodePools:
    nodepool-0:
      instanceType: t3a.xlarge
      rootVolumeSizeGB: 25
      minSize: 2
      maxSize: 5
      # Speed up the ASG cycle when upgrading to avoid having long running test case
      instanceWarmup: 180

  apps:
    certManager:
      values:
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "{{ .ClusterName }}-CertManager-Role"
        giantSwarmClusterIssuer:
          acme:
            http01:
              enabled: false
            dns01:
              route53:
                enabled: true
                region: eu-north-1
    clusterAutoscaler:
      values:
        configmap:
          # Prevent cluster-autoscaler from trying to scale down while we're in the middle of our scaling test
          scaleDownUnneededTime: 15m0s
